name: Build Unity Install Cache

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/cache-unity.yml'
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-cache-unity-project:
    runs-on: windows-latest

    env:
      workspace-path: "${{ github.workspace }}"
      source-path: "${{ github.workspace }}"
      release-path: "${{ github.workspace }}/tmp/release"
      add-packages-script-path: "${{ github.workspace }}/.github/workflow-scripts/add-user-package-to-vrc-get.js"
      get-serial-script-path: "${{ github.workspace }}/.github/workflow-scripts/get-serial-from-license-file.js"
      UNITY_SERIAL: XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
      UNITY_NO_SANDBOX: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Unity Editor
        if: runner.os == 'Windows'
        id: cache-unity
        uses: actions/cache@v4
        with:
          path: C:\Program Files\Unity\
          key: unity-editor-${{ runner.os }}-2022.3.22f1-${{ hashFiles('ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            unity-editor-${{ runner.os }}-2022.3.22f1-
            unity-editor-${{ runner.os }}-

      - name: Setup Unity
        if: steps.cache-unity.outputs.cache-hit != 'true'
        uses: kuler90/setup-unity@v1
        with:
          unity-modules: ${{ runner.os == 'Windows' && 'windows-il2cpp' || 'linux-il2cpp' }}
          unity-version: 2022.3.22f1
